version: '2'
services:
    php:
        build:
            context: ./.
            dockerfile: Dockerfile_local
        container_name: erp_php
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/current
        restart: always
    nginx:
        build: ./nginx
        container_name: erp_nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www/current
        restart: always
    mysql:
        image: mysql:5.6
        command: --default-authentication-plugin=mysql_native_password
        container_name: erp_mysql
        environment:
            MYSQL_DATABASE: erp
            MYSQL_USER: erp
            MYSQL_PASSWORD: erp
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
